### ISSUE TITLE
fix pipelines

### ISSUE THREAD

**Issue by black-snow** [haganjam/InvTraitR#19]
- [x] [use renv 1.0.0](https://github.com/haganjam/FW_invert_biomass_allometry/issues/25) - should fix ubuntu pipes
- [x] fix vignettes #26 
- [x] make macOS build work
- [x] stretch-goal: win builds

**Comment by black-snow** [comment]
![grafik](https://user-images.githubusercontent.com/579733/227726475-0352e15b-6968-4b2b-8312-ab27539dbe8f.png)

Finally we're in a good place to start :)

What's left to do:
* get it working on other platforms
* build+test against latest dependencies

**Comment by black-snow** [comment]
Wtf, broken again :D

**Comment by haganjam** [comment]
Yes, I don't know what's wrong here... All the tests run

**Comment by black-snow** [comment]
Apparently the `1.0.0` release of `renv` kicked our arses :)

**Comment by haganjam** [comment]
haha. Thanks a lot renv... goddammit.

**Comment by haganjam** [comment]
no, I genuiinely like renv

**Comment by black-snow** [comment]
Even with caching the pipelines are weirdly slow. Doesn't seem to fetch binaries when they are available. What I found on the web doesn't work on Linux. I'll ask for help.

**Comment by black-snow** [comment]
We're getting there. Linux builds are fine again (just awfully slow, still).
I'll take a look at macOS next.

**Comment by black-snow** [comment]
It seems to *just work*, but I'm [sceptic](https://github.com/rspatial/terra/issues/1253).
