### ISSUE TITLE
graphs need update

### ISSUE THREAD

**Issue by black-snow** [haganjam/InvTraitR#30]
With up2date dependencies I suddenly see:

> This graph was created by an old(er) igraph version.
  Call upgrade_graph() on it to use with the current igraph version
  For now we convert it on the fly...

a couple of times (e.g. when running `test()`). I guess it's one of the DB files ;)

**Comment by haganjam** [comment]
Do you want me to rebuild the database with the new igraph version?

**Comment by black-snow** [comment]
That'd be great. Those warnings might pop up for users otherwise as well.

**Comment by haganjam** [comment]
Done.
